### ISSUE TITLE
Recomendation aren't showing

### ISSUE THREAD

**Issue by JonyBepary** [maaa101/burgertunes#4]
I followed all the step. tried to change CSS theme & PORT. but it simply doesn't work.

![image](https://user-images.githubusercontent.com/12129117/209651921-c4725586-508d-4d9a-abe4-549ad0ee4f5e.png)
![image](https://user-images.githubusercontent.com/12129117/209651993-aee3b7f6-7476-430b-9434-ccb736ba6227.png)
![image](https://user-images.githubusercontent.com/12129117/209652140-99963786-575a-4cf9-87c6-df764e249ebc.png)

**Comment by maaa101** [comment]
Do you get any error messages?

**Comment by JonyBepary** [comment]
normally this error showed:
![image](https://user-images.githubusercontent.com/12129117/209997912-a4763778-26d5-4320-b374-8a140bd86d75.png)

so created a static/cache directory.
then no error showing
![image](https://user-images.githubusercontent.com/12129117/209998054-97b5b716-fc71-4690-807e-1328fc29a635.png)

this may happened to various dependency or file. can you provide a tested docker? it'll be much more convenient.

**Comment by JonyBepary** [comment]
Actually it doesn't work with my local machine. but works perfectly fine in replit instance.
